version: '3.8'

services:
  backend:
    build:
      context: ./node_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./node_backend:/app
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev
