
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.client
    command: npx vite

  backend:
    build: ./node_backend
    ports:
      - "5000:5000"
    volumes:
      - ./node_backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.node_backend
    command: npx tsx --tsconfig tsconfig.json src/server.ts

volumes:
  client_node_modules:
  backend_node_modules:
