version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"  # Vite frontend
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build: ./node_backend
    ports:
      - "5000:5000"  # Node backend
    volumes:
      - ./node_backend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
